#!/usr/bin/env php
<?php

//define('GERRIT_WEBSITE', (getenv("PLATFORM_CLI_ACCOUNTS_SITE") ?: "https://marketplace.commerceguys.com"));
define('GERRIT_WEBSITE', "https://gerrit.happyculture.coop");

// __DIR__ called in a class will point to the class directory. Saved now it
// ensure there's always a path to the cli root.
define('CLI_ROOT', __DIR__);

if (file_exists(CLI_ROOT . '/vendor/autoload.php')) {
    require CLI_ROOT . '/vendor/autoload.php';
} else {
    // we are globally installed via Composer
    require CLI_ROOT . '/../../autoload.php';
}

use Gerrit\GerritTools\Cli\Application;;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$application = new Application();
$application->run($input);
